import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/Nav";
import Rightpannel from "./components/Rightpannel";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <div className="flex h-screen w-full pt-16  ">
          <div className="overflow-hidden w-[30%]">
            <Nav />
          </div>
          <div className="flex-1 overflow-y-scroll  w-3/4 no-scrollbar">
            {children}
          </div>

          <div className=" overflow-hidden w-1/4">
            <Rightpannel />
          </div>
        </div>
      </body>
    </html>
  );
}
